# we are building using jekyll and use ruby
language: ruby
rvm:
- 2.3.3

sudo: false

# do not clone the entire history -- no old versions are needed
git:
  depth: 1

# but we need a few packages
addons:
  apt:
    packages:
    - openssh-client
    - rsync

install:
  # make sure we have all we need
  - which ssh-agent
  - which rsync

  # install github pages
  - gem install github-pages

script:
  # decrypt the ssh key
  - openssl aes-256-cbc -K $encrypted_803397f4ed6b_key -iv $encrypted_803397f4ed6b_iv -in .deploy/id_rsa.enc -out .deploy/id_rsa -d
  - chmod 600 .deploy/id_rsa

  # Disable stricvt host key checking
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  # start an ssh agent and add the key
  - eval $(ssh-agent -s)
  - ssh-add .deploy/id_rsa

  # build site
  - jekyll build -t _site

  # rsync everything from _site/
  - cd _site && rsync -rv -e ssh --checksum ./ deploy@server.jacobs-alumni.de:/var/www/jacobs-alumni.de --delete

branches:
  only:
  - master
