lida:
  applicantName: 'Lida-Maria-Lottko'
  position: 'Assessor PR & Communications'
  description: '<p>See her <a href="https://www.linkedin.com/in/lidamarialottko">LinkedIn profile</a>.</p>'
  pictureLink: 'who-we-are/elections/2017/Profile-picture-300x200.jpg'
  videoLink: 'https://drive.google.com/file/d/0B-Pk-gF-jlVdVW1XMDhLYkpjSHc/preview'
max:
  applicantName: 'Max Lohmann'
  position: 'Assessor Event Management'
  description: '<p>See his <a href="https://www.linkedin.com/in/max-lohmann-62440735">LinkedIn profile</a>.</p>'
  pictureLink: 'who-we-are/elections/2017/Max_Lohmann-300x205.png'
  videoLink: 'https://drive.google.com/a/jacobs-alumni.de/file/d/0B5SQg7EnyI03VGxTRjgwS2M3Nzg/preview'